name: Build and Test DevOps Assesment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
        
    - name: Test
      run: dotnet test DevOpsAssessment/DevOpsAssessment.sln --no-build --verbosity normal
      
    - name:  Build and Test DevOps Assesment
      uses: docker/login-action@v3.0.0
      with: .
        file: Api/Dockerfile
        tag: api:1.0
