name: Build and Test DevOps Assessment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
      
    - name: Test
      run: dotnet test DevOpsAssessment/DevOpsAssessment.sln --no-build --verbosity normal
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: github
        password: ${{ secrets.GH_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: DevOpsAssessment
        file: DevOpsAssessment/Api/Dockerfile
        tags: ghcr.io/jwili/devopsassessment:${{ github.sha }}
        push: true
        github-token: ${{ secrets.GH_TOKEN }}
